SELECT
  DATETIME(CONCAT(LEFT(CAST(VP.DATAVENDA AS string),4),"-",SUBSTRING(CAST(VP.DATAVENDA AS string),5,2),"-",RIGHT(CAST(VP.DATAVENDA AS string),2)," ",H.HORA,":",H.MINUTO,":00")) AS creationDate,
  VP.DATAVENDA,
  VP.NUMEROPEDIDOSITE,
  VP.CLIENTEKEY,
  VP.NUMEROPEDIDOCLIENTE,
  VP.CATEGORIACOMERCIAL,
  VP.TIPODEVENDA,
  VP.DEVICE,
  VP.FL_AVISTA,
  VP.FORMAPAGAMENTODETALHE,
  CN.CANAL_FINAL,
  VP.IDSELLERMARKETPLACE,
  VP.FLAG_1P_3P,
  VP.SUBCANAL,
  VP.QUANTIDADEFORMASPAGAMENTO,
  VP.QUANTIDADEPARCELAS,
  VP.PLATAFORMA,
  VP.FL_OURO,
  VP.FLAG_FRETE_GRATIS,
  VP.FL_REDE_SITE,
  VP.QUANTIDADEITENS,
  VP.VALORVENDA,
  VP.VALORCOMISSAO,
  VP.VALORCASHBACK,
  VP.CUSTOCOMERCIAL,
  (VP.VLICMS + VP.VLPISCOFINS + VP.VLICMSST) AS VALORIMPOSTOS,
  VP.VLFRETECLIENTEPROCESSADA,
  VP.VALORIMPOSTOFRETE,
  VP.VALORMVA,
  VP.CUSTOLIQUIDOCONTABIL,
  H.HORA,
  H.MINUTO,
  P.CODIGOIBM,
  P.FAMILIA,
  P.DESCRICAO,
  P.FORNECEDOR,
  P.MARCA,
  P.LINHA,
  P.GRUPO,
  P.SKUMARKETPLACE,
  SM.ASSISTIDO
FROM
  `maga-bigdata.dw.VW_FACT_VENDAS_PROCESSADAS` VP
LEFT JOIN
  `maga-bigdata.dw.VW_DIM_HORA` H
ON
  VP.HORARIOKEY = H.HORARIOKEY
LEFT JOIN
  `maga-bigdata.dw.VW_DIM_PRODUTO` P
ON
  VP.KEY_PRODUTO = P.KEY
LEFT JOIN
  `maga-bigdata.dw.VW_DIM_SELLER_MARKETPLACE` SM
ON
  VP.KEY_SELLER = SM.KEY_SELLER
LEFT JOIN
  `maga-bigdata.dw.VW_DIM_CATEGORIA_COMERCIAL` C
ON
  P.CATEGORIACOMERCIAL = C.CATEGORIACOMERCIAL

LEFT JOIN 
  `maga-bigdata.dw.VW_DIM_CANAL` CN
ON
  VP.SUBCANAL = CN.SUBCANAL
WHERE
  SM.CATEGORIA_MAGALU = "Beleza"
  AND DATE(CONCAT(LEFT(CAST(VP.DATAVENDA AS string),4),"-",SUBSTRING(CAST(VP.DATAVENDA AS string),5,2),"-",RIGHT(CAST(VP.DATAVENDA AS string),2))) >= DATE_ADD(CURRENT_DATE(), INTERVAL -35 DAY)
