SELECT
  DATETIME(CONCAT(LEFT(CAST(VP.DATAVENDA AS string),4),"-",SUBSTRING(CAST(VP.DATAVENDA AS string),5,2),"-",RIGHT(CAST(VP.DATAVENDA AS string),2)," ",H.HORA,":",H.MINUTO,":00")) AS creationDate,
  VP.DATAVENDA,
  VP.NUMEROPEDIDOSITE,
  VP.CLIENTEKEY,
  VP.NUMEROPEDIDOCLIENTE,
  VP.CATEGORIACOMERCIAL,
  VP.TIPODEVENDA,
  VP.DEVICE,
  VP.FL_AVISTA,
  VP.FORMAPAGAMENTODETALHE,
  CN.CANAL_FINAL,
  VP.IDSELLERMARKETPLACE,
  VP.FLAG_1P_3P,
  VP.SUBCANAL,
  VP.QUANTIDADEFORMASPAGAMENTO,
  VP.QUANTIDADEPARCELAS,
  VP.PLATAFORMA,
  VP.FL_OURO,
  VP.FLAG_FRETE_GRATIS,
  VP.FL_REDE_SITE,
  VP.QUANTIDADEITENS,
  VP.VALORVENDA,
  VP.VALORCOMISSAO,
  VP.VALORCASHBACK,
  VP.CUSTOCOMERCIAL,
  (VP.VLICMS + VP.VLPISCOFINS + VP.VLICMSST) AS VALORIMPOSTOS,
  VP.CUSTOLIQUIDOCONTABIL,
  VP.VLFRETECLIENTEPROCESSADA,
  VP.VALORIMPOSTOFRETE,
  VP.VALORMVA,
  H.HORA,
  H.MINUTO,
  P.CODIGOIBM,
  P.FAMILIA,
  P.DESCRICAO,
  P.FORNECEDOR,
  P.MARCA,
  P.LINHA,
  P.GRUPO,
  P.SKUMARKETPLACE,
  SM.ASSISTIDO
FROM
  (SELECT 
  
    CASE WHEN
    (CASE WHEN VPRO.FLEVENTO = 'T' THEN  VPRO.FILIALCANCELAMENTO ELSE VPRO.FILIALKEY END) IN (200,660) THEN 1
    ELSE 2 END                                                                                   AS FL_REDE_SITE,
    CASE WHEN (CASE WHEN VPRO.FLEVENTO = 'T' THEN  VPRO.FILIALCANCELAMENTO ELSE VPRO.FILIALKEY END) IN (200,660) 
          THEN VPRO.DATACOMPETENCIAKEY
          ELSE CAST(SUBSTR(REPLACE(CAST(VPRO.DATAINCLUSAO AS STRING),'-',''),1,8) AS INT) END    AS DATAVENDA,

    CASE WHEN (CASE WHEN VPRO.FLEVENTO = 'T' THEN  VPRO.FILIALCANCELAMENTO ELSE VPRO.FILIALKEY END) IN (200,660) 
          THEN VPRO.NUMEROPEDIDOSITE 
          ELSE VPRO.NUMEROPEDIDOITEM END                                                         AS NUMEROPEDIDOSITE,

    CLI.KEY                                                                                      AS CLIENTEKEY,		
    VPRO.numeropedidocliente                                                                     AS NUMEROPEDIDOCLIENTE,    
    IFNULL (VPRO.CATEGORIACOMERCIAL,'NA')                                                        AS CATEGORIACOMERCIAL, 
    PROD.KEY                                                                                     AS KEY_PRODUTO,
    CASE VPRO.FLEVENTO
			WHEN 'V' THEN 'VENDA'
			WHEN 'C' THEN 'CANCELAMENTO'
			WHEN 'T' THEN 'TROCA'
			WHEN 'D' THEN 'DEVOLUÇÃO'
			ELSE VPRO.FLEVENTO 
		END                                                                                          AS TIPODEVENDA,
    VPRO.HORARIOPEDIDOKEY                                                                        AS HORARIOKEY,	
    CASE 
      WHEN UPPER (VPRO.DEVICE) LIKE ('%APP%')             THEN 'APP'     
		  WHEN UPPER (VPRO.DEVICE) LIKE ('%MOBILE%')          THEN 'SITE MOBILE'     
		  WHEN UPPER (VPRO.DEVICE) LIKE ('%DESKTOP B2C%')     THEN 'DESKTOP B2C'     
		  WHEN UPPER (VPRO.DEVICE) LIKE ('%DESKTOP%')         THEN 'DESKTOP OUTROS' 
		  WHEN UPPER (VPRO.DEVICE) LIKE ('%OUTRO%')           THEN 'DESKTOP OUTROS'     
		  ELSE  'DESKTOP OUTROS' END                                                                 AS DEVICE,	   
    IFNULL(TRIM(UPPER (VCAPSUB.FORMAPAGAMENTO)),'N/A')                                           AS FORMAPAGAMENTODETALHE,
    'MAGAZINELUIZA'                                                                              AS IDSELLERMARKETPLACE,
    SEL.KEY                                       											 		                     AS KEY_SELLER,
     CASE WHEN UPPER(INTER.linha) like 'MKTPLACE (LOJA)%' THEN '3P' ELSE '1P' END                 AS FLAG_1P_3P,
    CASE    
      WHEN UPPER (VPRO.CANALECOMM) = 'SSG'                                                    		  THEN 'SAMSUNG' 
      WHEN LOWER(VPRO.CANALORIGEM) = 'mobile vendas (loja)'                                   		  THEN 'PARCEIRO 0' 
      WHEN LOWER(VPRO.CANALORIGEM) = 'juntos - ios'                                   		       THEN 'JUNTOS - ANDROID'  
      WHEN LOWER(VPRO.CANALORIGEM) = 'juntos - android'                                   		  THEN 'JUNTOS - IOS'            
      WHEN UPPER (VPRO.CANALECOMM) IN ('TELEVENDAS','TELEVENDAS - PF')                        		  THEN 'TELEVENDAS - PF' 
      WHEN UPPER (VPRO.CANALECOMM) IN ('TELEVENDAS - PJ','B2B - VENDAS CORPORATIVAS')         		  THEN 'TELEVENDAS - PJ'
      WHEN UPPER (VPRO.CANALORIGEM) = 'B2B - PORTAL MAGALU EMPRESAS'                          		  THEN 'B2B - PORTAL M EMPRESAS'           
      WHEN UPPER (VPRO.CANALECOMM) LIKE '%B2B%' AND UPPER (VPRO.PARCEIRONOME) LIKE '%CLUBE%'  		  THEN 'B2B - CLUBES' 
      WHEN UPPER (VPRO.CANALECOMM) LIKE '%B2B%' AND UPPER (VPRO.PARCEIRONOME) LIKE '%SHOP%'   		  THEN 'B2B - SHOPPING' 
      WHEN UPPER (VPRO.CANALECOMM) LIKE '%B2B%'                                               		  THEN 'B2B - PROGRAMAS'      
      WHEN UPPER (VPRO.CANALECOMM) LIKE '%NN - MVC%' 		
        OR UPPER (VPRO.PARCEIRONOME) LIKE '%CANALTECH%' 		
        OR UPPER (VPRO.PARCEIRONOME) LIKE '%DESCONTOMATE%'                                    		  THEN 'MAGAZINE VOCÊ'                
      WHEN UPPER (VPRO.PARCEIRONOME) LIKE 'PLA%' AND UPPER(VPRO.CANALPARCEIRO) = 'MIDIA'      		  THEN 'MIDIA - PLA' 
      WHEN UPPER (VPRO.PARCEIRONOME) LIKE 'FACEBO%' AND UPPER (VPRO.CANALPARCEIRO) = 'MIDIA'  		  THEN 'MIDIA - SOCIAL ADS'
      WHEN REGEXP_CONTAINS (UPPER (VPRO.PARCEIRONOME), 'B.GO|MB.GO|B.YA|MB.YA|S.GO') 		
                                                     AND UPPER (VPRO.CANALPARCEIRO) = 'MIDIA' 		  THEN 'MIDIA - BUSCADORES BRANDING' 
      WHEN UPPER (VPRO.PARCEIRONOME) LIKE 'DPA %' AND UPPER (VPRO.CANALPARCEIRO) = 'MIDIA'    		  THEN 'MIDIA - REMARKETING DPA' 
      WHEN UPPER (VPRO.PARCEIRONOME) LIKE 'BUST%' AND UPPER (VPRO.CANALPARCEIRO) = 'MIDIA'    		  THEN 'MIDIA - COMPARADOR BUSCAPE' 
      WHEN UPPER (VPRO.PARCEIRONOME) LIKE 'GOOG%' AND UPPER (VPRO.CANALPARCEIRO) = 'MIDIA'    		  THEN 'MIDIA - BUSCADOR DSA'       
      WHEN UPPER (VPRO.PARCEIRONOME) LIKE 'ZOOM - BANCO PAN' 		
                                                 AND UPPER (VPRO.CANALPARCEIRO) = 'MIDIA'     		  THEN 'MIDIA - ZOOM CPA'       
      WHEN UPPER (VPRO.PARCEIRONOME) LIKE 'ZOOC%' AND UPPER (VPRO.CANALPARCEIRO) = 'MIDIA'    		  THEN 'MIDIA - ZOOM CPA'
      WHEN UPPER (VPRO.PARCEIRONOME) LIKE 'ZOOM%' AND UPPER (VPRO.CANALPARCEIRO) = 'MIDIA'    		  THEN 'MIDIA - ZOOM CPC'  
      WHEN UPPER (VPRO.PARCEIRONOME) LIKE 'I.CRIT%' AND UPPER (VPRO.CANALPARCEIRO) = 'MIDIA'  		  THEN 'MIDIA - CRITEO IN APP'
      WHEN UPPER (VPRO.PARCEIRONOME) LIKE '%CRITEO%' AND UPPER (VPRO.CANALPARCEIRO) = 'MIDIA' 		  THEN 'MIDIA - CRITEO' 
      WHEN UPPER (VPRO.SUBCANALPARCEIRO) = 'DISPLAY' AND UPPER (VPRO.CANALPARCEIRO) = 'MIDIA' 		  THEN 'MIDIA - DISPLAY' 
      WHEN UPPER (VPRO.PARCEIRONOME) LIKE ('TIK TOK%') AND UPPER (VPRO.CANALPARCEIRO) = 'MIDIA'       THEN 'MIDIA - SOCIAL ADS'
      WHEN UPPER (VPRO.PARCEIRONOME) LIKE 'TIK TOK%' AND UPPER (VPRO.CANALPARCEIRO) = 'MIDIA'         THEN 'MIDIA - SOCIAL ADS'
      WHEN UPPER (VPRO.PARCEIRONOME) LIKE 'PINTEREST%' AND UPPER (VPRO.CANALPARCEIRO) = 'MIDIA'       THEN 'MIDIA - SOCIAL ADS'
      WHEN UPPER (VPRO.PARCEIRONOME) LIKE 'FB%' AND UPPER (VPRO.CANALPARCEIRO) = 'MIDIA'              THEN 'MIDIA - SOCIAL ADS'      
      WHEN UPPER (VPRO.PARCEIRONOME) LIKE 'SNAPCHAT%' AND UPPER (VPRO.CANALPARCEIRO) = 'MIDIA'        THEN 'MIDIA - SOCIAL ADS'
      WHEN UPPER (VPRO.PARCEIRONOME) LIKE 'TWITTER%' AND UPPER (VPRO.CANALPARCEIRO) = 'MIDIA'         THEN 'MIDIA - SOCIAL ADS'
      WHEN UPPER (VPRO.PARCEIRONOME) LIKE 'SOCIAL ADS%' AND UPPER (VPRO.CANALPARCEIRO) = 'MIDIA'      THEN 'MIDIA - SOCIAL ADS' 
      WHEN UPPER (VPRO.PARCEIRONOME) LIKE 'JACOTEI%' AND UPPER (VPRO.CANALPARCEIRO) = 'MIDIA'         THEN 'MIDIA - JACOTEI CPA'      
      WHEN UPPER (VPRO.PARCEIRONOME) LIKE 'SC.GOOGLE%' AND UPPER (VPRO.CANALPARCEIRO) = 'MIDIA'       THEN 'MIDIA - BUSCADOR SHOWCASE'  
      WHEN UPPER (VPRO.CANALPARCEIRO)= 'MIDIA'                                                        THEN 'MIDIA - OUTROS' 
      WHEN UPPER (VPRO.PARCEIRONOME) IN ('WPP_SHARE_PDP','WPP_SHARE_PDP_MOBILE')                      THEN 'PARCEIRO 0'
      WHEN UPPER (VPRO.PARCEIRONOME) LIKE 'WPP_%'                                                     THEN 'CRM - WHATSAPP'     
/*      WHEN UPPER (VPRO.CANALPARCEIRO)= 'CRM' AND UPPER (VPRO.SUBCANALPARCEIRO) = 'PUSH'
                                             AND UPPER (VPRO.PARCEIRONOME) LIKE ('PUSH_INAPP_%')      THEN 'PUSH - INAPP' 
      WHEN UPPER (VPRO.CANALPARCEIRO)= 'CRM' AND UPPER (VPRO.SUBCANALPARCEIRO) = 'PUSH'
                                             AND UPPER (VPRO.PARCEIRONOME) LIKE ('PUSH_IN_AUT_%')     THEN 'PUSH - INAPP' 
      WHEN UPPER (VPRO.CANALPARCEIRO)= 'CRM' AND UPPER (VPRO.SUBCANALPARCEIRO) = 'PUSH'
                                             AND UPPER (VPRO.PARCEIRONOME) LIKE ('PUSH_AUT_INAPP%')   THEN 'PUSH - INAPP' */                                                                                         
      WHEN UPPER (VPRO.CANALPARCEIRO)= 'CRM' AND UPPER (VPRO.SUBCANALPARCEIRO) = 'PUSH'             
                                             AND UPPER (VPRO.PARCEIRONOME) LIKE ('PUSH_BLT%')         THEN 'PUSH - BLAST'
      WHEN UPPER (VPRO.CANALPARCEIRO)= 'CRM' AND UPPER (VPRO.SUBCANALPARCEIRO) = 'PUSH'             
                                             AND UPPER (VPRO.PARCEIRONOME) LIKE ('PUSH_SEG%')         THEN 'PUSH - BLAST'                                               
      WHEN UPPER (VPRO.CANALPARCEIRO)= 'CRM' AND UPPER (VPRO.SUBCANALPARCEIRO) = 'PUSH'             
                                             AND UPPER (VPRO.PARCEIRONOME) LIKE ('PUSH_BOB%')         THEN 'PUSH - BOBBY REC' 
      WHEN UPPER (VPRO.CANALPARCEIRO)= 'CRM' AND UPPER (VPRO.SUBCANALPARCEIRO) = 'PUSH'             
                                             AND UPPER (VPRO.PARCEIRONOME) LIKE ('BOB_PUSH%')         THEN 'PUSH - BOBBY REC'
      WHEN UPPER (VPRO.CANALPARCEIRO)= 'CRM' AND UPPER (VPRO.SUBCANALPARCEIRO) = 'PUSH'
                                             AND UPPER (VPRO.PARCEIRONOME) LIKE ('PUSH_URBAN%')       THEN 'PUSH - URBAN REC' 
--      WHEN UPPER (VPRO.CANALPARCEIRO)= 'CRM' AND UPPER (VPRO.SUBCANALPARCEIRO) = 'PUSH'             
--                                             AND UPPER (VPRO.PARCEIRONOME) LIKE ('PUSH_MSC%')         THEN 'PUSH - MSC' 
      WHEN UPPER (VPRO.CANALPARCEIRO)= 'CRM' AND UPPER (VPRO.SUBCANALPARCEIRO) = 'PUSH' 
                                             AND UPPER (VPRO.PARCEIRONOME) NOT LIKE ('PUSH_AUT_INAPP%')            
                                             AND UPPER (VPRO.PARCEIRONOME) LIKE ('PUSH_AUT_%')     THEN 'PUSH - JORNADA' 
      WHEN UPPER (VPRO.CANALPARCEIRO)= 'CRM' AND UPPER (VPRO.SUBCANALPARCEIRO) = 'PUSH'             
                                             AND UPPER (VPRO.PARCEIRONOME) LIKE ('PUSH_OURO%')        THEN 'PUSH - JORNADA' 
      WHEN UPPER (VPRO.CANALPARCEIRO)= 'CRM' AND UPPER (VPRO.SUBCANALPARCEIRO) = 'PUSH'             
                                             AND UPPER (VPRO.PARCEIRONOME) LIKE ('PUSH_JORNADA%')     THEN 'PUSH - JORNADA' 
      WHEN UPPER (VPRO.CANALPARCEIRO)= 'CRM' AND UPPER (VPRO.SUBCANALPARCEIRO) = 'PUSH'             
                                             AND UPPER (VPRO.PARCEIRONOME) LIKE ('PUSH_MPAY%')        THEN 'PUSH - JORNADA'                                              
      WHEN UPPER (VPRO.CANALPARCEIRO)= 'CRM' AND UPPER (VPRO.SUBCANALPARCEIRO) = 'PUSH'
                                             AND UPPER (VPRO.PARCEIRONOME) NOT LIKE ('PUSH_INAPP_%')  
                                             AND UPPER (VPRO.PARCEIRONOME) NOT LIKE ('PUSH_IN_AUT_%')                                              
                                             AND UPPER (VPRO.PARCEIRONOME) NOT LIKE ('PUSH_AUT_INAPP%')   
                                             AND UPPER (VPRO.PARCEIRONOME) NOT LIKE ('PUSH_MSC%')   THEN 'PUSH - OUTROS'
      WHEN UPPER (VPRO.CANALPARCEIRO)= 'CRM' AND UPPER (VPRO.PARCEIRONOME) NOT LIKE ('PUSH_INAPP_%')  
                                             AND UPPER (VPRO.PARCEIRONOME) NOT LIKE ('PUSH_IN_AUT_%')                                              
                                             AND UPPER (VPRO.PARCEIRONOME) NOT LIKE ('PUSH_AUT_INAPP%')   
                                             AND UPPER (VPRO.PARCEIRONOME) NOT LIKE ('PUSH_MSC%')   THEN 'CRM - EMAIL'   
      
            ELSE 'PARCEIRO 0'  END                                                                AS SUBCANAL,
    IFNULL(VCAPSUB.QUANTIDADEFORMASPAGAMENTO,0)                                                  AS QUANTIDADEFORMASPAGAMENTO,
    IFNULL(VCAPSUB.QUANTIDADEPARCELAS,0)                                                         AS QUANTIDADEPARCELAS,
    CASE 
      WHEN VCAPSUB.QUANTIDADEPARCELAS = 1 THEN 'SIM' ELSE  'NÃO'  END                            AS FL_AVISTA,
    UPPER(IFNULL(VCAPSUB.PLATAFORMA,'NA'))                                                       AS PLATAFORMA,
    CASE WHEN ifnull(CO.KEY, 0) = 0 THEN 'NÃO' ELSE 'SIM' END                                    AS FL_OURO,
    CASE WHEN VPRO.VLFRETE = 0 THEN 'SIM' ELSE 'NÃO' END                                         AS FLAG_FRETE_GRATIS,
    
    --MEDIDAS       
    IFNULL(VPRO.CUSTOINVENTARIO, 0) * 	IFNULL (VPRO.QUANTIDADEITENS, 0)                         AS CUSTOLIQUIDOCONTABIL,
    IFNULL(VPRO.VLFRETE ,0)                                                                      AS VLFRETECLIENTEPROCESSADA,		
        
 IF(VPRO.DATACOMPETENCIAKEY = CAST(REPLACE(CAST(CURRENT_DATE() AS STRING),"-","") AS INT64), 
 ROUND(-IFNULL (IFNULL(IMPHJ.ICMS_PRODUTO,0) + IFNULL(IMPHJ.IMPOSTOS_FRETE_BRUTO_DEV,0), IFNULL(JV.ICMS_REB_PEDIDO,0) + IFNULL(JV.IMPOSTOS_FRETE_CM,0) ),1),
 ROUND(-IFNULL (IFNULL(IMP.ICMS_PRODUTO,0) + IFNULL(IMP.IMPOSTOS_FRETE_BRUTO_DEV,0), IFNULL(JV.ICMS_REB_PEDIDO,0) + IFNULL(JV.IMPOSTOS_FRETE_CM,0) ),1)) AS VLICMS,
 
 
 IF(VPRO.DATACOMPETENCIAKEY = CAST(REPLACE(CAST(CURRENT_DATE() AS STRING),"-","") AS INT64),
 ROUND(-IFNULL (IMPHJ.PIS_COFINS_PRODUTO, IFNULL(JV.PIS_COFINS_REB_PEDIDO,0) )  ,1),
 ROUND(-IFNULL (IMP.PIS_COFINS_PRODUTO, IFNULL(JV.PIS_COFINS_REB_PEDIDO,0) )  ,1))                          AS VLPISCOFINS,

IF(VPRO.DATACOMPETENCIAKEY = CAST(REPLACE(CAST(CURRENT_DATE() AS STRING),"-","") AS INT64),
 ROUND(IFNULL (IMPHJ.ICMS_ST_PRODUTO, IFNULL(-JV.ICMS_ST_CM,0))                 ,1),
 ROUND(IFNULL (IMP.ICMS_ST_PRODUTO, IFNULL(-JV.ICMS_ST_CM,0))                 ,1))                          AS VLICMSST,

    CASE 
      WHEN VPRO.FLEVENTO = 'V' 
      THEN IFNULL (VPRO.QUANTIDADEITENS,0) 
      ELSE -(IFNULL (VPRO.QUANTIDADEITENS,0)) END                                                AS QUANTIDADEITENS,
    
  
    CASE WHEN (CASE WHEN VPRO.FLEVENTO = 'T' THEN  VPRO.FILIALCANCELAMENTO ELSE VPRO.FILIALKEY END) IN (200,660) 
         THEN (IFNULL(VPRO.PRECOUNITARIOLIQUIDO, 0) * IFNULL(VPRO.QUANTIDADEITENS, 0)) + IFNULL(VPRO.VLFRETE, 0)
         WHEN VPRO.TIPOVENDAKEY IN(1,2,3,4) AND IFNULL(VPRO.CONSIDERARESULTADOLOJA, 'S') = 'S'
         THEN (IFNULL(VPRO.VLVENDARESULTADO,0) * IFNULL(VPRO.QUANTIDADEITENS,0)) --+ IFNULL(VPRO.VLFRETE, 0) 
         ELSE 0 END                                                                             AS VALORVENDA, 

	   0                                                                                           AS VALORCOMISSAO,
     IFNULL(VPRO.CUSTOCOMERCIAL, 0)	                                                              AS CUSTOCOMERCIAL,
    CASE WHEN VPRO.FLEVENTO = 'V' AND (CASE WHEN VPRO.FLEVENTO = 'T' THEN  VPRO.FILIALCANCELAMENTO ELSE VPRO.FILIALKEY END) IN (200,660)
          THEN IFNULL(VPRO.QUANTIDADEITENS,0)  * IFNULL (VCAPSUB.VLCASHBACK,0) 
          WHEN (CASE WHEN VPRO.FLEVENTO = 'T' THEN  VPRO.FILIALCANCELAMENTO ELSE VPRO.FILIALKEY END) IN (200,660)
          THEN IFNULL(VPRO.QUANTIDADEITENS,0)  * IFNULL (VCAPSUB.VLCASHBACK,0) * -1
          ELSE IFNULL(CASH.VALOR_BENEFICIO,0) END                                                 AS VALORCASHBACK,     
          

IF(VPRO.DATACOMPETENCIAKEY = CAST(REPLACE(CAST(CURRENT_DATE() AS STRING),"-","") AS INT64),
 IFNULL((ABS(IMPHJ.MVA_POSITIVO_PRODUTO) - ABS(IMPHJ.MVA_NEGATIVO_PRODUTO)), IFNULL((MVA_POSITIVO_CM + MVA_NEGATIVO_CM),0)),
 IFNULL((ABS(IMP.MVA_POSITIVO_PRODUTO) - ABS(IMP.MVA_NEGATIVO_PRODUTO)), IFNULL((MVA_POSITIVO_CM + MVA_NEGATIVO_CM),0)))  AS VALORMVA,

IF(VPRO.DATACOMPETENCIAKEY = CAST(REPLACE(CAST(CURRENT_DATE() AS STRING),"-","") AS INT64),
 -IFNULL(IMPHJ.IMPOSTOS_FRETE_BRUTO_DEV, IMPOSTOS_FRETE_CM),
 -IFNULL(IMP.IMPOSTOS_FRETE_BRUTO_DEV, IMPOSTOS_FRETE_CM) )                                                       AS VALORIMPOSTOFRETE

  FROM `maga-bigdata.apolo.vw_fact_vendas_processadas`  VPRO
  LEFT JOIN (
	            SELECT	DISTINCT NUMEROPEDIDO, PRODUTOSITEKEY,hashunicocliente, 
              PRODUTOKEY,IDSELLERMARKETPLACE,FIDELIZACAO,BUNDLE, PLATAFORMA, 
              MLENTREGA,TIPOCASHBACK,TIPOCOMPREGANHE,FILIALRETIRALOJA, VLFRETECLIENTENOMINAL,VLFRETEMAGAZINE,VLFRETEMAGAZINENOMINAL,   
              VLICMS, VLPISCOFINS, VLICMSST, QUANTIDADEFORMASPAGAMENTO,FORMAPAGAMENTO, QUANTIDADEPARCELAS,CIDADEENTREGA,VLCASHBACK,VLCOMPREGANHE 
			        FROM `maga-bigdata.apolo.vw_fact_vendas_captadas`
	            WHERE UPPER(STATUS) <> 'TESTE' AND UPPER (IDSELLERMARKETPLACE) = 'MAGAZINELUIZA' 
             )  VCAPSUB 
	          ON VPRO.NUMEROPEDIDOSITE = VCAPSUB.NUMEROPEDIDO AND VPRO.PRODUTOKEY = VCAPSUB.PRODUTOKEY   
            
  LEFT JOIN `maga-bigdata.dw.VW_APURACAO_IMPOSTO_PROCESSADO_DIA_ATUAL` IMPHJ ON  IMPHJ.NUMEROPEDIDOITEM = VPRO.NUMEROPEDIDOITEM
                                                                           AND IMPHJ.produtokey = VPRO.PRODUTOKEY
                                                                           AND IMPHJ.flevento = VPRO.flevento
                                                                           AND IMPHJ.DATACOMPETENCIAKEY = VPRO.DATACOMPETENCIAKEY
                                                                           AND IFNULL(IMPHJ.NUMERONOVOPEDIDOITEM, -1) = IFNULL(VPRO.NUMERONOVOPEDIDOITEM, -1)
                                                                           AND IFNULL(IMPHJ.datacancelamento, '1900-01-01') = IFNULL(VPRO.datacancelamento,'1900-01-01')
                                                                           AND IMPHJ.horariopedidokey = VPRO.horariopedidokey

  LEFT JOIN `maga-bigdata.dw.APURACAO_IMPOSTO_PROCESSADO` IMP ON               IMP.NUMEROPEDIDOITEM = VPRO.NUMEROPEDIDOITEM
                                                                           AND IMP.produtokey = VPRO.PRODUTOKEY
                                                                           AND IMP.flevento = VPRO.flevento
                                                                           AND IMP.DATACOMPETENCIAKEY = VPRO.DATACOMPETENCIAKEY
                                                                           AND IFNULL(IMP.NUMERONOVOPEDIDOITEM, -1) = IFNULL(VPRO.NUMERONOVOPEDIDOITEM, -1)
                                                                           AND IFNULL(IMP.datacancelamento, '1900-01-01') = IFNULL(VPRO.datacancelamento,'1900-01-01')
                                                                           AND IMP.horariopedidokey = VPRO.horariopedidokey

  LEFT JOIN `maga-bigdata.dw.dim_produto` INTER 
       ON INTER.PRODUTOKEY = VPRO.PRODUTOKEY

  LEFT JOIN `maga-bigdata.dw.TB_DIM_PRODUTO`  PROD  
	   ON CONCAT(UPPER(CAST(INTER.CODIGOIBM AS STRING)),UPPER('MAGAZINELUIZA')) = CONCAT(UPPER(PROD.PRODUTOKEY),UPPER(PROD.SELLERKEY))
	
  LEFT JOIN `maga-bigdata.dw.TB_DIM_SELLER_MARKETPLACE`  SEL  
	   ON UPPER('MAGAZINELUIZA') = UPPER(SEL.idsellermarketplace)
	
  LEFT JOIN `maga-bigdata.dw.TB_DIM_CLIENTE`  CLI  
        ON UPPER(IFNULL(VCAPSUB.hashunicocliente, VPRO.hashunicocliente)) = UPPER(CLI.hashunicocliente)  
  
  LEFT JOIN `maga-bigdata.bi_ecomm.TB_AUX_DDV_CG_REDE` CASH 
      ON CASH.NUMEROPEDIDO = CAST(VPRO.NUMEROPEDIDOITEM AS STRING) 
      AND CASH.CODIGOIBM = UPPER(CAST(INTER.CODIGOIBM AS STRING)) 
      AND UPPER(TIPO_BENEFICIO) = UPPER('cashback')

   LEFT JOIN `maga-bigdata.dw.VW_AUX_CLIENTE_OURO` CO ON CO.KEY = CLI.KEY  
        AND CO.DATAKEY <= VPRO.DATACOMPETENCIAKEY
       
   LEFT JOIN `maga-bigdata.dw.VW_FACT_VENDAS_PROCESSADAS_JARVIS_1P` JV
       ON VPRO.CLIENTEKEY = JV.CLIENTEKEY
      AND VPRO.VENDEDORKEY = JV.VENDEDORKEY
      AND VPRO.PRODUTOKEY = JV.PRODUTOKEY
      AND VPRO.LINHAKEY= JV.LINHAKEY
      AND VPRO.FAMILIAKEY= JV.FAMILIAKEY
      AND VPRO.TIPOVENDAKEY= JV.TIPOVENDAKEY
      AND VPRO.FILIALKEY= JV.FILIALKEY
      AND VPRO.FILIALSAIDAKEY= JV.FILIALSAIDAKEY
      AND VPRO.DATAPEDIDOKEY= JV.DATAPEDIDOKEY
      AND VPRO.DATACOMPETENCIAKEY= JV.DATACOMPETENCIAKEY
      AND VPRO.HORARIOPEDIDOKEY= JV.HORARIOPEDIDOKEY
      --AND VPRO.NUMEROPEDIDOCLIENTE= JV.NUMEROPEDIDOCLIENTE
      AND VPRO.NUMEROPEDIDOITEM= JV.NUMEROPEDIDOITEM
      AND VPRO.NUMEROPEDIDOPRINCIPAL= JV.NUMEROPEDIDOPRINCIPAL
      AND VPRO.NUMERONOVOPEDIDOITEM= JV.NUMERONOVOPEDIDOITEM
      AND VPRO.NUMEROCANCELAMENTO= JV.NUMEROCANCELAMENTO
      AND VPRO.FLEVENTO= JV.FL_EVENTO
    
UNION ALL
SELECT 
  1                                                                                                AS FL_REDE_SITE, 
	CAST(FORMAT_DATE('%Y%m%d',CAST(VCAP.Datapagamentomktp AS DATE)) AS INT64)                        AS DATAVENDA,
	VCAP.NUMEROPEDIDO                                                                                AS NUMEROPEDIDO,
	CLI.KEY                                                                                          AS CLIENTEKEY,		
	VCAP.numeropedidocliente                                                                         AS NUMEROPEDIDOCLIENTE,	
	IFNULL(DEPARA.CATEGORIACOMERCIAL,'NA')                                                           AS CATEGORIACOMERCIAL,
	PROD.KEY                                                                                         AS KEY_PRODUTO, 
	'VENDA'                                                                                          AS TIPODEVENDA ,
	IFNULL((CAST(FORMAT_DATETIME('%H',CAST(VCAP.Datapagamentomktp AS DATETIME)) AS INT64) * 60) + CAST(FORMAT_DATETIME('%M',CAST(VCAP.Datapagamentomktp AS DATETIME)) AS INT64),0)                   AS HORARIOKEY,		
	CASE WHEN UPPER (VCAP.DEVICE) LIKE ('%APP%')          THEN 'APP'     
		 WHEN UPPER (VCAP.DEVICE) LIKE ('%MOBILE%')       THEN 'SITE MOBILE'     
		 WHEN UPPER (VCAP.DEVICE) LIKE ('%DESKTOP B2C%')  THEN 'DESKTOP B2C'     
		 WHEN UPPER (VCAP.DEVICE) LIKE ('%DESKTOP%')      THEN 'DESKTOP OUTROS' 
		 WHEN UPPER (VCAP.DEVICE) LIKE ('%OUTRO%')        THEN 'DESKTOP OUTROS'     
		 ELSE UPPER (VCAP.DEVICE) END                    	                                              AS DEVICE,	
	IFNULL(TRIM(UPPER(VCAP.FORMAPAGAMENTO)),'N/A')                                                    AS FORMAPAGAMENTODETALHE,
	UPPER(VCAP.IDSELLERMARKETPLACE)                											 		                          AS IDSELLERMARKETPLACE,
	SEL.KEY                                       											 		                          AS KEY_SELLER,
	'3P' 									                                                                            AS FLAG_1P_3P,
    CASE    
      WHEN UPPER (VCAP.CANALECOMM) = 'SSG'                                                    		  THEN 'SAMSUNG' 
      WHEN LOWER(VCAP.CANALORIGEM) = 'mobile vendas (loja)'                                   		  THEN 'PARCEIRO 0' 
      WHEN LOWER(VCAP.CANALORIGEM) = 'juntos - ios'                                   		          THEN 'JUNTOS - ANDROID'  
      WHEN LOWER(VCAP.CANALORIGEM) = 'juntos - android'                                   		      THEN 'JUNTOS - IOS'         
      WHEN UPPER (VCAP.CANALECOMM) IN ('TELEVENDAS','TELEVENDAS - PF')                        		  THEN 'TELEVENDAS - PF' 
      WHEN UPPER (VCAP.CANALECOMM) IN ('TELEVENDAS - PJ','B2B - VENDAS CORPORATIVAS')         		  THEN 'TELEVENDAS - PJ'
      WHEN UPPER (VCAP.CANALORIGEM) = 'B2B - PORTAL MAGALU EMPRESAS'                          		  THEN 'B2B - PORTAL M EMPRESAS'           
      WHEN UPPER (VCAP.CANALECOMM) LIKE '%B2B%' AND UPPER (VCAP.PARCEIRONOME) LIKE '%CLUBE%'  		  THEN 'B2B - CLUBES' 
      WHEN UPPER (VCAP.CANALECOMM) LIKE '%B2B%' AND UPPER (VCAP.PARCEIRONOME) LIKE '%SHOP%'   		  THEN 'B2B - SHOPPING' 
      WHEN UPPER (VCAP.CANALECOMM) LIKE '%B2B%'                                               		  THEN 'B2B - PROGRAMAS'      
      WHEN UPPER (VCAP.CANALECOMM) LIKE '%NN - MVC%' 		
        OR UPPER (VCAP.PARCEIRONOME) LIKE '%CANALTECH%' 		
        OR UPPER (VCAP.PARCEIRONOME) LIKE '%DESCONTOMATE%'                                    		  THEN 'MAGAZINE VOCÊ'                
      WHEN UPPER (VCAP.PARCEIRONOME) LIKE 'PLA%' AND UPPER(VCAP.CANALPARCEIRO) = 'MIDIA'      		  THEN 'MIDIA - PLA' 
      WHEN UPPER (VCAP.PARCEIRONOME) LIKE 'FACEBO%' AND UPPER (VCAP.CANALPARCEIRO) = 'MIDIA'  		  THEN 'MIDIA - SOCIAL ADS'
      WHEN REGEXP_CONTAINS (UPPER (VCAP.PARCEIRONOME), 'B.GO|MB.GO|B.YA|MB.YA|S.GO') 		
                                                     AND UPPER (VCAP.CANALPARCEIRO) = 'MIDIA' 		  THEN 'MIDIA - BUSCADORES BRANDING' 
      WHEN UPPER (VCAP.PARCEIRONOME) LIKE 'DPA %' AND UPPER (VCAP.CANALPARCEIRO) = 'MIDIA'    		  THEN 'MIDIA - REMARKETING DPA' 
      WHEN UPPER (VCAP.PARCEIRONOME) LIKE 'BUST%' AND UPPER (VCAP.CANALPARCEIRO) = 'MIDIA'    		  THEN 'MIDIA - COMPARADOR BUSCAPE' 
      WHEN UPPER (VCAP.PARCEIRONOME) LIKE 'GOOG%' AND UPPER (VCAP.CANALPARCEIRO) = 'MIDIA'    		  THEN 'MIDIA - BUSCADOR DSA'       
      WHEN UPPER (VCAP.PARCEIRONOME) LIKE 'ZOOM - BANCO PAN' 		
                                                 AND UPPER (VCAP.CANALPARCEIRO) = 'MIDIA'     		  THEN 'MIDIA - ZOOM CPA'       
      WHEN UPPER (VCAP.PARCEIRONOME) LIKE 'ZOOC%' AND UPPER (VCAP.CANALPARCEIRO) = 'MIDIA'    		  THEN 'MIDIA - ZOOM CPA'
      WHEN UPPER (VCAP.PARCEIRONOME) LIKE 'ZOOM%' AND UPPER (VCAP.CANALPARCEIRO) = 'MIDIA'    		  THEN 'MIDIA - ZOOM CPC'  
      WHEN UPPER (VCAP.PARCEIRONOME) LIKE 'I.CRIT%' AND UPPER (VCAP.CANALPARCEIRO) = 'MIDIA'  		  THEN 'MIDIA - CRITEO IN APP'
      WHEN UPPER (VCAP.PARCEIRONOME) LIKE '%CRITEO%' AND UPPER (VCAP.CANALPARCEIRO) = 'MIDIA' 		  THEN 'MIDIA - CRITEO' 
      WHEN UPPER (VCAP.SUBCANALPARCEIRO) = 'DISPLAY' AND UPPER (VCAP.CANALPARCEIRO) = 'MIDIA' 		  THEN 'MIDIA - DISPLAY' 
      WHEN UPPER (VCAP.PARCEIRONOME) LIKE ('TIK TOK%') AND UPPER (VCAP.CANALPARCEIRO) = 'MIDIA'     THEN 'MIDIA - SOCIAL ADS'
      WHEN UPPER (VCAP.PARCEIRONOME) LIKE 'TIK TOK%' AND UPPER (VCAP.CANALPARCEIRO) = 'MIDIA'       THEN 'MIDIA - SOCIAL ADS'
      WHEN UPPER (VCAP.PARCEIRONOME) LIKE 'PINTEREST%' AND UPPER (VCAP.CANALPARCEIRO) = 'MIDIA'     THEN 'MIDIA - SOCIAL ADS'
      WHEN UPPER (VCAP.PARCEIRONOME) LIKE 'FB%' AND UPPER (VCAP.CANALPARCEIRO) = 'MIDIA'            THEN 'MIDIA - SOCIAL ADS'      
      WHEN UPPER (VCAP.PARCEIRONOME) LIKE 'SNAPCHAT%' AND UPPER (VCAP.CANALPARCEIRO) = 'MIDIA'      THEN 'MIDIA - SOCIAL ADS'
      WHEN UPPER (VCAP.PARCEIRONOME) LIKE 'TWITTER%' AND UPPER (VCAP.CANALPARCEIRO) = 'MIDIA'       THEN 'MIDIA - SOCIAL ADS'
      WHEN UPPER (VCAP.PARCEIRONOME) LIKE 'SOCIAL ADS%' AND UPPER (VCAP.CANALPARCEIRO) = 'MIDIA'    THEN 'MIDIA - SOCIAL ADS' 
      WHEN UPPER (VCAP.PARCEIRONOME) LIKE 'JACOTEI%' AND UPPER (VCAP.CANALPARCEIRO) = 'MIDIA'       THEN 'MIDIA - JACOTEI CPA'      
      WHEN UPPER (VCAP.PARCEIRONOME) LIKE 'SC.GOOGLE%' AND UPPER (VCAP.CANALPARCEIRO) = 'MIDIA'     THEN 'MIDIA - BUSCADOR SHOWCASE'  
      WHEN UPPER (VCAP.CANALPARCEIRO)= 'MIDIA'                                                      THEN 'MIDIA - OUTROS' 
      WHEN UPPER (VCAP.PARCEIRONOME) IN ('WPP_SHARE_PDP','WPP_SHARE_PDP_MOBILE')                    THEN 'PARCEIRO 0'
      WHEN UPPER (VCAP.PARCEIRONOME) LIKE 'WPP_%'                                                   THEN 'CRM - WHATSAPP'     
/*      WHEN UPPER (VCAP.CANALPARCEIRO)= 'CRM' AND UPPER (VCAP.SUBCANALPARCEIRO) = 'PUSH'
                                             AND UPPER (VCAP.PARCEIRONOME) LIKE ('PUSH_INAPP_%')    THEN 'PUSH - INAPP' 
      WHEN UPPER (VCAP.CANALPARCEIRO)= 'CRM' AND UPPER (VCAP.SUBCANALPARCEIRO) = 'PUSH'
                                             AND UPPER (VCAP.PARCEIRONOME) LIKE ('PUSH_IN_AUT_%')   THEN 'PUSH - INAPP' 
      WHEN UPPER (VCAP.CANALPARCEIRO)= 'CRM' AND UPPER (VCAP.SUBCANALPARCEIRO) = 'PUSH'
                                             AND UPPER (VCAP.PARCEIRONOME) LIKE ('PUSH_AUT_INAPP%') THEN 'PUSH - INAPP' */                                                                                         
      WHEN UPPER (VCAP.CANALPARCEIRO)= 'CRM' AND UPPER (VCAP.SUBCANALPARCEIRO) = 'PUSH'             
                                             AND UPPER (VCAP.PARCEIRONOME) LIKE ('PUSH_BLT%')       THEN 'PUSH - BLAST'
      WHEN UPPER (VCAP.CANALPARCEIRO)= 'CRM' AND UPPER (VCAP.SUBCANALPARCEIRO) = 'PUSH'             
                                             AND UPPER (VCAP.PARCEIRONOME) LIKE ('PUSH_SEG%')       THEN 'PUSH - BLAST'                                               
      WHEN UPPER (VCAP.CANALPARCEIRO)= 'CRM' AND UPPER (VCAP.SUBCANALPARCEIRO) = 'PUSH'             
                                             AND UPPER (VCAP.PARCEIRONOME) LIKE ('PUSH_BOB%')       THEN 'PUSH - BOBBY REC' 
      WHEN UPPER (VCAP.CANALPARCEIRO)= 'CRM' AND UPPER (VCAP.SUBCANALPARCEIRO) = 'PUSH'             
                                             AND UPPER (VCAP.PARCEIRONOME) LIKE ('BOB_PUSH%')       THEN 'PUSH - BOBBY REC'
      WHEN UPPER (VCAP.CANALPARCEIRO)= 'CRM' AND UPPER (VCAP.SUBCANALPARCEIRO) = 'PUSH'
                                             AND UPPER (VCAP.PARCEIRONOME) LIKE ('PUSH_URBAN%')     THEN 'PUSH - URBAN REC' 
--      WHEN UPPER (VCAP.CANALPARCEIRO)= 'CRM' AND UPPER (VCAP.SUBCANALPARCEIRO) = 'PUSH'             
--                                             AND UPPER (VCAP.PARCEIRONOME) LIKE ('PUSH_MSC%')       THEN 'PUSH - MSC' 
      WHEN UPPER (VCAP.CANALPARCEIRO)= 'CRM' AND UPPER (VCAP.SUBCANALPARCEIRO) = 'PUSH' 
                                             AND UPPER (VCAP.PARCEIRONOME) NOT LIKE ('PUSH_AUT_INAPP%')            
                                             AND UPPER (VCAP.PARCEIRONOME) LIKE ('PUSH_AUT_%')     THEN 'PUSH - JORNADA' 
      WHEN UPPER (VCAP.CANALPARCEIRO)= 'CRM' AND UPPER (VCAP.SUBCANALPARCEIRO) = 'PUSH'             
                                             AND UPPER (VCAP.PARCEIRONOME) LIKE ('PUSH_OURO%')      THEN 'PUSH - JORNADA' 
      WHEN UPPER (VCAP.CANALPARCEIRO)= 'CRM' AND UPPER (VCAP.SUBCANALPARCEIRO) = 'PUSH'             
                                             AND UPPER (VCAP.PARCEIRONOME) LIKE ('PUSH_JORNADA%')   THEN 'PUSH - JORNADA' 
      WHEN UPPER (VCAP.CANALPARCEIRO)= 'CRM' AND UPPER (VCAP.SUBCANALPARCEIRO) = 'PUSH'             
                                             AND UPPER (VCAP.PARCEIRONOME) LIKE ('PUSH_MPAY%')      THEN 'PUSH - JORNADA'                                              
      WHEN UPPER (VCAP.CANALPARCEIRO)= 'CRM' AND UPPER (VCAP.SUBCANALPARCEIRO) = 'PUSH'
                                             AND UPPER (VCAP.PARCEIRONOME) NOT LIKE ('PUSH_INAPP_%')  
                                             AND UPPER (VCAP.PARCEIRONOME) NOT LIKE ('PUSH_IN_AUT_%')                                              
                                             AND UPPER (VCAP.PARCEIRONOME) NOT LIKE ('PUSH_AUT_INAPP%')   
                                             AND UPPER (VCAP.PARCEIRONOME) NOT LIKE ('PUSH_MSC%')   THEN 'PUSH - OUTROS'
      WHEN UPPER (VCAP.CANALPARCEIRO)= 'CRM' AND UPPER (VCAP.PARCEIRONOME) NOT LIKE ('PUSH_INAPP_%')  
                                             AND UPPER (VCAP.PARCEIRONOME) NOT LIKE ('PUSH_IN_AUT_%')                                              
                                             AND UPPER (VCAP.PARCEIRONOME) NOT LIKE ('PUSH_AUT_INAPP%')   
                                             AND UPPER (VCAP.PARCEIRONOME) NOT LIKE ('PUSH_MSC%')   THEN 'CRM - EMAIL'  
      
            ELSE 'PARCEIRO 0'  END                                                                AS SUBCANAL,
	IFNULL(VCAP.QUANTIDADEFORMASPAGAMENTO,0)                                                       AS QUANTIDADEFORMASPAGAMENTO,
	IFNULL(VCAP.QUANTIDADEPARCELAS,0)                                                              AS QUANTIDADEPARCELAS,
	CASE WHEN VCAP.QUANTIDADEPARCELAS = 1 THEN 'SIM' ELSE  'NÃO'	END	  				                   AS FL_AVISTA,
    UPPER(IFNULL(VCAP.PLATAFORMA,'NA'))   													                             AS PLATAFORMA,
    CASE WHEN ifnull(CO.KEY, 0) = 0 THEN 'NÃO' ELSE 'SIM' END                                    AS FL_OURO,
	CASE WHEN CAST (VCAP.VLFRETECLIENTENOMINAL AS  FLOAT64) = 0 THEN 'SIM' ELSE 'NÃO' END          AS FLAG_FRETE_GRATIS,

	--MEDIDAS 
   	IFNULL(VCAP.CUSTOCOMERCIAL,0) * IFNULL (VCAP.QUANTIDADEITENS,0) 						                 AS CUSTOLIQUIDOCONTABIL,
	CAST (VCAP.VLFRETECLIENTENOMINAL AS NUMERIC)										                               AS VLFRETECLIENTEPROCESSADA,
	
	ROUND(CAST (VCAP.VLICMS AS NUMERIC)           ,1)			                                         AS VLICMS,	  
	ROUND(CAST (VCAP.VLPISCOFINS AS NUMERIC) 			,1)								                               AS VLPISCOFINS,
	ROUND(CAST (VCAP.VLICMSST AS NUMERIC) 				,1)								                               AS VLICMSST,   
	IFNULL(VCAP.QUANTIDADEITENS,0)														                                     AS QUANTIDADEITENS,	
	IFNULL(VCAP.VLVENDAITEM,0) - IFNULL(VCAP.VLDESCONTOAVISTA,0) + IFNULL(VCAP.VLJUROS,0) + IFNULL(VCAP.VLFRETECLIENTE,0) AS VALORVENDA,
	0 																								                                             AS VALORSERVICO,
  IFNULL(VCAP.CUSTOCOMERCIAL,0)															                                     AS CUSTOCOMERCIAL,
    IFNULL(VCAP.QUANTIDADEITENS,0)  * IFNULL (VCAP.VLCASHBACK,0)  																AS VALORCASHBACK,
  0 AS VALORMVA,
  0 AS VALORIMPOSTOFRETE

	FROM `maga-bigdata.apolo.vw_fact_vendas_captadas` VCAP
  
	LEFT JOIN (SELECT CHAVE, MAX(COD_CATEGORIA_COMERCIAL) CATEGORIACOMERCIAL 
                 FROM `maga-bigdata.bi_adm.DE_PARA_CATEGORIA_3P` GROUP BY CHAVE) DEPARA 
        ON DEPARA.CHAVE = CONCAT(VCAP.CATEGORIA,VCAP.SUBCATEGORIA) 
       
	LEFT JOIN `maga-bigdata.dw.TB_DIM_PRODUTO`  PROD  
		    ON CONCAT(UPPER(VCAP.PRODUTOMARKETPLACEKEY),UPPER(VCAP.IDSELLERMARKETPLACE)) = CONCAT(UPPER(PROD.PRODUTOKEY),UPPER(PROD.SELLERKEY))	
	
  LEFT JOIN `maga-bigdata.dw.TB_DIM_SELLER_MARKETPLACE`  SEL  
		   ON UPPER(VCAP.IDSELLERMARKETPLACE) = UPPER(SEL.idsellermarketplace)	
       
	LEFT JOIN `maga-bigdata.dw.TB_DIM_CLIENTE`  CLI  
		   ON UPPER(VCAP.hashunicocliente) = UPPER(CLI.hashunicocliente)  
       
       
   LEFT JOIN `maga-bigdata.dw.VW_AUX_CLIENTE_OURO` CO ON CO.KEY = CLI.KEY  
       AND CO.DATAKEY <= VCAP.DATAPEDIDOKEY
      


  WHERE UPPER(VCAP.STATUS) <> 'TESTE'
  AND UPPER (IFNULL(VCAP.IDSELLERMARKETPLACE,'-1')) <> 'MAGAZINELUIZA'  
  AND VCAP.Datapagamentomktp IS NOT NULL 
  AND VCAP.NUMEROPEDIDOCLIENTE NOT IN (SELECT DISTINCT B.NUMEROPEDIDOCLIENTE FROM `maga-bigdata.dw.fact_pedidos_blacklist` B)) VP

LEFT JOIN
  `maga-bigdata.dw.VW_DIM_HORA` H
ON
  VP.HORARIOKEY = H.HORARIOKEY
LEFT JOIN
  `maga-bigdata.dw.VW_DIM_PRODUTO` P
ON
  VP.KEY_PRODUTO = P.KEY
LEFT JOIN
  `maga-bigdata.dw.VW_DIM_SELLER_MARKETPLACE` SM
ON
  VP.KEY_SELLER = SM.KEY_SELLER
LEFT JOIN
  `maga-bigdata.dw.VW_DIM_CATEGORIA_COMERCIAL` C
ON
  P.CATEGORIACOMERCIAL = C.CATEGORIACOMERCIAL

LEFT JOIN 
  `maga-bigdata.dw.VW_DIM_CANAL` CN
ON
  VP.SUBCANAL = CN.SUBCANAL
WHERE
  C.VERTICAL = "BELEZA"
  AND DATE(CONCAT(LEFT(CAST(VP.DATAVENDA AS string),4),"-",SUBSTRING(CAST(VP.DATAVENDA AS string),5,2),"-",RIGHT(CAST(VP.DATAVENDA AS string),2))) >= DATE_ADD(CURRENT_DATE(), INTERVAL -35 DAY)
